In [2]:
from src.ingest import load_info, load_links

In [8]:
df_info = load_info()
df_info.head()

,string_protein_id,preferred_name,protein_size,annotation
0,9606.ENSP00000000233,ARF5,180,ADP-ribosylation factor 5; GTP-binding protein...
1,9606.ENSP00000000412,M6PR,277,Cation-dependent mannose-6-phosphate receptor;...
2,9606.ENSP00000001008,FKBP4,459,"Peptidyl-prolyl cis-trans isomerase FKBP4, N-t..."
3,9606.ENSP00000001146,CYP26B1,512,Cytochrome P450 26B1; Involved in the metaboli...
4,9606.ENSP00000002125,NDUFAF7,441,"Protein arginine methyltransferase NDUFAF7, mi..."

In [9]:
df_links = load_links()
df_links.head()

               protein1              protein2  combined_score
0  9606.ENSP00000000233  9606.ENSP00000356607             173
1  9606.ENSP00000000233  9606.ENSP00000427567             154
2  9606.ENSP00000000233  9606.ENSP00000253413             151
3  9606.ENSP00000000233  9606.ENSP00000493357             471
4  9606.ENSP00000000233  9606.ENSP00000324127             201